import React from 'react'
import i1 from '../../../public/sjc.jpg'
import Image from 'next/image'
import gsap from 'gsap'

export default function page() {
  return (
    <div className='header'>
        <h1 className='text-center justify-center mt-5 text-blue-700 text-7xl text font-mono shadow-lg shadow-blue-500'>CAREER</h1>
    <div className='body flex flex-row flex-initial mt-5 '>
    <div className='w-1/4'><Image className='ml-3' src={i1} width={400} height={400}></Image></div>
    <div className='text flex-column ml-10 w-3/4 h-32'>
    <p className='text-slate-300 tracking-widest'><div className='t1 font-semibold text-white'> PRE-APPLE</div> <br></br>

In February 1974, Jobs returned to his parents' home in Los Altos and began looking for a job. He was soon hired by Atari, Inc. in Los Gatos, California, as a computer technician. Back in 1973, Steve Wozniak designed his own version of the classic video game Pong and gave its electronics board to Jobs. According to Wozniak, Atari only hired Jobs because he took the board down to the company, and they thought that he had built it himself.Atari's cofounder Nolan Bushnell later described him as "difficult but valuable", pointing out that "he was very often the smartest guy in the room, and he would let people know that".

Jobs traveled to India in mid-1974 to visit Neem Karoli Baba at his Kainchi ashram with his Reed friend (and eventual Apple employee) Daniel Kottke, searching for spiritual enlightenment. When they got to the Neem Karoli ashram, it was almost deserted because Neem Karoli Baba had died in September 1973. Then they made a long trek up a dry riverbed to an ashram of Haidakhan Babaji.

After seven months, Jobs left India and returned to the US ahead of Daniel Kottke. Jobs had changed his appearance; his head was shaved, and he wore traditional Indian clothing. During this time, Jobs experimented with psychedelics, later calling his LSD experiences "one of the two or three most important things [he had] done in [his] life". He spent a period at the All One Farm, a commune in Oregon that was owned by Robert Friedland.

During this time period, Jobs and Brennan both became practitioners of Zen Buddhism through the Zen master Kōbun Chino Otogawa. Jobs engaged in lengthy meditation retreats at the Tassajara Zen Mountain Center, the oldest Sōtō Zen monastery in the US. He considered taking up monastic residence at Eihei-ji in Japan, and maintained a lifelong appreciation for Zen, Japanese cuisine, and artists such as Hasui Kawase.

Jobs returned to Atari in early 1975, and that summer, Bushnell assigned him to create a circuit board for the arcade video game Breakout in as few chips as possible, knowing that Jobs would recruit Wozniak for help. During his day job at HP, Wozniak drew sketches of the circuit design; at night, he joined Jobs at Atari and continued to refine the design, which Jobs implemented on a breadboard. According to Bushnell, Atari offered $100 (equivalent to about $500 in 2022) for each TTL chip that was eliminated in the machine. Jobs made a deal with Wozniak to split the fee evenly between them if Wozniak could minimize the number of chips. Much to the amazement of Atari engineers, within four days Wozniak reduced the TTL count to 45, far below the usual 100, though Atari later re-engineered it to make it easier to test and add a few missing features. According to Wozniak, Jobs told him that Atari paid them only $750 (instead of the actual $5,000), and that Wozniak's share was thus $375. Wozniak did not learn about the actual bonus until ten years later but said that if Jobs had told him about it and explained that he needed the money, Wozniak would have given it to him.

Jobs and Wozniak attended meetings of the Homebrew Computer Club in 1975, which was a steppingstone to the development and marketing of the first Apple computer.

According to a document released by the DoD, circa 1975, Steve Jobs claims he was arrested in Eugene, Oregon after being questioned for being a minor in possession of alcohol. Jobs alleges that he "didn't have any alcohol", but police questioned him, and subsequently determined that he had an outstanding arrest warrant for an unpaid speeding ticket. Jobs claims he then paid the approximately $50 fine. The arrest allegedly occurred "behind a store". </p><br></br>!!!

<p className='text-slate-300 tracking-widest'><div className='t1 font-semibold text-white'> APPLE(1976-1985) </div><br></br>By March 1976, Wozniak completed the basic design of the Apple I computer and showed it to Jobs, who suggested that they sell it; Wozniak was at first skeptical of the idea but later agreed. In April of that same year, Jobs, Wozniak, and administrative overseer Ronald Wayne founded Apple Computer Company (now called "Apple Inc.") as a business partnership in Jobs's parents' Crist Drive home on April 1, 1976. The operation originally started in Jobs's bedroom and later moved to the garage. Wayne stayed briefly, leaving Jobs and Wozniak as the active primary cofounders of the company.

The two decided on the name "Apple" after Jobs returned from the All One Farm commune in Oregon and told Wozniak about his time in the farm's apple orchard. Jobs originally planned to produce bare printed circuit boards of the Apple I and sell them to computer hobbyists for $50 (equivalent to about $260 in 2022) each. To fund the first batch, Wozniak sold his HP scientific calculator and Jobs sold his Volkswagen van. Later that year, computer retailer Paul Terrell purchased 50 fully assembled Apple I units for $500 each. Eventually about 200 Apple I computers were produced in total.
A neighbor on Crist Drive recalled Jobs as an odd individual who would greet his clients "with his underwear hanging out, barefoot and hippie-like". Another neighbor, Larry Waterland, who had just earned his PhD in chemical engineering at Stanford, recalled dismissing Jobs's budding business compared to the established industry of giant mainframe computers with big decks of punch cards: "Steve took me over to the garage. He had a circuit board with a chip on it, a DuMont TV set, a Panasonic cassette tape deck and a keyboard. He said, 'This is an Apple computer.' I said, 'You've got to be joking.' I dismissed the whole idea." Jobs's friend from Reed College and India, Daniel Kottke, recalled that as an early Apple employee, he "was the only person who worked in the garage … Woz would show up once a week with his latest code. Steve Jobs didn't get his hands dirty in that sense." Kottke also stated that much of the early work took place in Jobs's kitchen, where he spent hours on the phone trying to find investors for the company.

They received funding from a then-semi-retired Intel product marketing manager and engineer Mike Markkula. Scott McNealy, one of the cofounders of Sun Microsystems, said that Jobs broke a "glass age ceiling" in Silicon Valley because he'd created a very successful company at a young age. Markkula brought Apple to the attention of Arthur Rock, which after looking at the crowded Apple booth at the Home Brew Computer Show, started with a $60,000 investment and went on the Apple board. Jobs was not pleased when Markkula recruited Mike Scott from National Semiconductor in February 1977 to serve as the first president and CEO of Apple.
By early 1985, the Macintosh's failure to defeat the IBM PC became clear, and it strengthened Sculley's position in the company. In May 1985, Sculley—encouraged by Arthur Rock—decided to reorganize Apple, and proposed a plan to the board that would remove Jobs from the Macintosh group and put him in charge of "New Product Development". This move would effectively render Jobs powerless within Apple. In response, Jobs then developed a plan to get rid of Sculley and take over Apple. However, Jobs was confronted after the plan was leaked, and he said that he would leave Apple. The Board declined his resignation and asked him to reconsider. Sculley also told Jobs that he had all of the votes needed to go ahead with the reorganization. A few months later, on September 17, 1985, Jobs submitted a letter of resignation to the Apple Board. Five additional senior Apple employees also resigned and joined Jobs in his new venture, NeXT.

The Macintosh's struggle continued after Jobs left Apple. Though marketed and received in fanfare, the expensive Macintosh was hard to sell. In 1985, Bill Gates's then-developing company, Microsoft, threatened to stop developing Mac applications unless it was granted "a license for the Mac operating system software. Microsoft was developing its graphical user interface ... for DOS, which it was calling Windows and didn't want Apple to sue over the similarities between the Windows GUI and the Mac interface." Sculley granted Microsoft the license which later led to problems for Apple.[ In addition, cheap IBM PC clones that ran Microsoft software and had a graphical user interface began to appear. Although the Macintosh preceded the clones, it was far more expensive, so "through the late 1980s, the Windows user interface was getting better and better and was thus taking increasingly more share from Apple". Windows-based IBM-PC clones also led to the development of additional GUIs such as IBM's TopView or Digital Research's GEM, and thus "the graphical user interface was beginning to be taken for granted, undermining the most apparent advantage of the Mac...it seemed clear as the 1980s wound down that Apple couldn't go it alone indefinitely against the whole IBM-clone market".</p> <br></br>

<p className='text-slate-300 tracking-widest'><div className='t1 font-semibold text-white'> NeXT computer(1985-1997)</div> <br></br>
    Following his resignation from Apple in 1985, Jobs founded NeXT Inc. with $7 million. A year later he was running out of money, and he sought venture capital with no product on the horizon. Eventually, Jobs attracted the attention of billionaire Ross Perot, who invested heavily in the company. The NeXT computer was shown to the world in what was considered Jobs's comeback event, a lavish invitation-only gala launch event that was described as a multimedia extravaganza. The celebration was held at the Louise M. Davies Symphony Hall, San Francisco, California, on Wednesday, October 12, 1988. Steve Wozniak said in a 2013 interview that while Jobs was at NeXT he was "really getting his head together".

NeXT workstations were first released in 1990 and priced at $9,999 (equivalent to about $22,000 in 2022). Like the Apple Lisa, the NeXT workstation was technologically advanced and designed for the education sector but was largely dismissed as cost prohibitive. The NeXT workstation was known for its technical strengths, chief among them its object-oriented software development system. Jobs marketed NeXT products to the financial, scientific, and academic community, highlighting its innovative, experimental new technologies, such as the Mach kernel, the digital signal processor chip, and the built-in Ethernet port. Making use of a NeXT computer, English computer scientist Tim Berners-Lee invented the World Wide Web in 1990 at CERN in Switzerland.

The revised, second generation NeXTcube was released in 1990. Jobs touted it as the first "interpersonal" computer that would replace the personal computer. With its innovative NeXTMail multimedia email system, NeXTcube could share voice, image, graphics, and video in email for the first time. "Interpersonal computing is going to revolutionize human communications and groupwork", Jobs told reporters.Jobs ran NeXT with an obsession for aesthetic perfection, as evidenced by the development of and attention to NeXTcube's magnesium case. This put considerable strain on NeXT's hardware division, and in 1993, after having sold only 50,000 machines, NeXT transitioned fully to software development with the release of NeXTSTEP/Intel. The company reported its first yearly profit of $1.03 million in 1994. In 1996, NeXT Software, Inc. released WebObjects, a framework for Web application development. After NeXT was acquired by Apple Inc. in 1997, WebObjects was used to build and run the Apple Store, MobileMe services, and the iTunes Store. 
</p><br></br>

<p className='text-slate-300 tracking-widest'><div className='t1 font-semibold text-white'> Pixar and Disney</div> <br></br>In 1986, Jobs funded the spinout of The Graphics Group (later renamed Pixar) from Lucasfilm's computer graphics division for the price of $10 million, $5 million of which was given to the company as capital and $5 million of which was paid to Lucasfilm for technology rights.
Jobs with Pixar team at the Oval Office in November 1998

The first film produced by Pixar with its Disney partnership, Toy Story (1995), with Jobs credited as executive producer, brought financial success and critical acclaim to the studio when it was released. Over the course of Jobs's life, under Pixar's creative chief John Lasseter, the company produced box-office hits A Bug's Life (1998), Toy Story 2 (1999), Monsters, Inc. (2001), Finding Nemo (2003), The Incredibles (2004), Cars (2006), Ratatouille (2007), WALL-E (2008), Up (2009), Toy Story 3 (2010), and Cars 2 (2011). Brave (2012), Pixar's first film to be produced since Jobs's death, honored him with a tribute for his contributions to the studio. Finding Nemo, The Incredibles, Ratatouille, WALL-E, Up, Toy Story 3, and Brave each received the Academy Award for Best Animated Feature, an award introduced in 2001.

In 2003 and 2004, as Pixar's contract with Disney was running out, Jobs and Disney chief executive Michael Eisner tried but failed to negotiate a new partnership, and in January 2004, Jobs announced that he would never deal with Disney again. Pixar would seek a new partner to distribute its films after its contract expired.

In October 2005, Bob Iger replaced Eisner at Disney, and Iger quickly worked to mend relations with Jobs and Pixar. On January 24, 2006, Jobs and Iger announced that Disney had agreed to purchase Pixar in an all-stock transaction worth $7.4 billion. When the deal closed, Jobs became The Walt Disney Company's largest single shareholder with approximately seven percent of the company's stock. Jobs's holdings in Disney far exceeded those of Eisner, who holds 1.7%, and of Disney family member Roy E. Disney, who until his 2009 death held about 1% of the company's stock and whose criticisms of Eisner—especially that he soured Disney's relationship with Pixar—accelerated Eisner's ousting. Upon completion of the merger, Jobs received 7% of Disney shares, and joined the board of directors as the largest individual shareholder. Upon Jobs's death his shares in Disney were transferred to the Steven P. Jobs Trust led by Laurene Jobs.

After Jobs's death, Iger recalled in 2019 that many warned him about Jobs, "that he would bully me and everyone else". Iger wrote, "Who wouldn't want Steve Jobs to have influence over how a company is run?", and that as an active Disney board member "he rarely created trouble for me. Not never but rarely". He speculated that they would have seriously considered merging Disney and Apple had Jobs lived. Floyd Norman, of Pixar, described Jobs as a "mature, mellow individual" who never interfered with the creative process of the filmmakers. In early June 2014, Pixar cofounder and Walt Disney Animation Studios President Ed Catmull revealed that Jobs once advised him to "just explain it to them until they understand" in disagreements. Catmull released the book Creativity, Inc. in 2014, in which he recounts numerous experiences of working with Jobs. Regarding his own manner of dealing with Jobs, Catmull writes:

    In all the 26 years with Steve, Steve and I never had one of these loud verbal arguments, and it's not my nature to do that. … but we did disagree fairly frequently about things. … I would say something to him and he would immediately shoot it down because he could think faster than I could. … I would then wait a week … I'd call him up, and I give my counterargument to what he had said, and he'd immediately shoot it down. So I had to wait another week, and occasionally this went on for months. But ultimately one of three things happened. About a third of the time he said, "Oh, I get it, you're right", and that was the end of it. And it was another third of the time in which [I'd] say, "Actually I think he is right". The other third of the time, where we didn't reach consensus, he just let me do it my way, never said anything more about it.
</p> <br></br>

<p className='text-slate-300 tracking-widest'><div className='t1 font-semibold text-white'> Return to Apple(1997-2011)</div><br></br>
In 1996, Apple announced that it would buy NeXT for $400 million. The deal was finalized in February 1997, bringing Jobs back to the company he had cofounded. Jobs became de facto chief after then-CEO Gil Amelio was ousted in July 1997. He was formally named interim chief executive on September 16. In March 1998, to concentrate Apple's efforts on returning to profitability, Jobs terminated several projects, such as Newton, Cyberdog, and OpenDoc. In the coming months, many employees developed a fear of encountering Jobs while riding in the elevator, "afraid that they might not have a job when the doors opened. The reality was that Jobs's summary executions were rare, but a handful of victims was enough to terrorize a whole company." Jobs changed the licensing program for Macintosh clones, making it too costly for the manufacturers to continue making machines.

With the purchase of NeXT, much of the company's technology found its way into Apple products, most notably NeXTSTEP, which evolved into Mac OS X. Under Jobs's guidance, the company increased sales significantly with the introduction of the iMac and other new products; since then, appealing designs and powerful branding have worked well for Apple. At the 2000 Macworld Expo, Jobs officially dropped the "interim" modifier from his title at Apple and became permanent CEO. Jobs quipped at the time that he would be using the title "iCEO".

The company subsequently branched out, introducing and improving upon other digital appliances. With the introduction of the iPod portable music player, iTunes digital music software, and the iTunes Store, the company made forays into consumer electronics and music distribution. On June 29, 2007, Apple entered the cellular phone business with the introduction of the iPhone, a multi-touch display cell phone, which also included the features of an iPod and, with its own mobile browser, revolutionized the mobile browsing scene. While nurturing open-ended innovation, Jobs also reminded his employees that "real artists ship".

Jobs had a public war of words with Dell Computer CEO Michael Dell, starting in 1987, when Jobs first criticized Dell for making "un-innovative beige boxes". On October 6, 1997, at a Gartner Symposium, when Dell was asked what he would do if he ran the then-troubled Apple Computer company, he said: "I'd shut it down and give the money back to the shareholders". Then, in 2006, Jobs emailed all employees when Apple's market capitalization rose above Dell's. It read:

    Team, it turned out that Michael Dell wasn't perfect at predicting the future. Based on today's stock market close, Apple is worth more than Dell. Stocks go up and down, and things may be different tomorrow, but I thought it was worth a moment of reflection today. Steve.]

Jobs was both admired and criticized for his consummate skill at persuasion and salesmanship, which has been dubbed the "reality distortion field" and was particularly evident during his keynote speeches (colloquially known as "Stevenotes") at Macworld Expos and at Apple Worldwide Developers Conferences.

Jobs usually went to work wearing a black long-sleeved mock turtleneck made by Issey Miyake, Levi's 501 blue jeans, and New Balance 991 sneakers.[149] Jobs told his biographer Walter Isaacson "...he came to like the idea of having a uniform for himself, both because of its daily convenience (the rationale he claimed) and its ability to convey a signature style".

Jobs was a board member at Gap Inc. from 1999 to 2002.
Two men in their fifties shown full length sitting in red leather chairs smiling at each other
Jobs and Bill Gates at the fifth D: All Things Digital conference (D5) in May 2007

In 2001, Jobs was granted stock options in the amount of 7.5 million shares of Apple with an exercise price of $18.30. It was alleged that the options had been backdated, and that the exercise price should have been $21.10. It was further alleged that Jobs had thereby incurred taxable income of $20,000,000 that he did not report, and that Apple overstated its earnings by that same amount. As a result, Jobs potentially faced a number of criminal charges and civil penalties. The case was the subject of active criminal and civil government investigations, though an independent internal Apple investigation completed on December 29, 2006, found that Jobs was unaware of these issues and that the options granted to him were returned without being exercised in 2003.

In 2005, Jobs responded to criticism of Apple's poor recycling programs for e-waste in the US by lashing out at environmental and other advocates at Apple's annual meeting in Cupertino in April. A few weeks later, Apple announced it would take back iPods for free at its retail stores. The Computer TakeBack Campaign responded by flying a banner from a plane over the Stanford University graduation at which Jobs was the commencement speaker. The banner read "Steve, don't be a mini-player—recycle all e-waste".

In 2006, he further expanded Apple's recycling programs to any US customer who buys a new Mac. This program includes shipping and "environmentally friendly disposal" of their old systems. The success of Apple's unique products and services provided several years of stable financial returns, propelling Apple to become the world's most valuable publicly traded company in 2011.

Jobs was perceived as a demanding perfectionist who always aspired to position his businesses and their products at the forefront of the information technology industry by foreseeing and setting innovation and style trends. He summed up this self-concept at the end of his keynote speech at the Macworld Conference and Expo in January 2007, by quoting ice hockey player Wayne Gretzky:

    There's an old Wayne Gretzky quote that I love. "I skate to where the puck is going to be, not where it has been". And we've always tried to do that at Apple. Since the very, very beginning. And we always will.

Jobs demonstrating the iPhone 4 to Russian President Dmitry Medvedev on June 23, 2010

On July 1, 2008, a $7 billion class action suit was filed against several members of the Apple board of directors for revenue lost because of alleged securities fraud.

In a 2011 interview with biographer Walter Isaacson, Jobs revealed that he had met with US President Barack Obama, complained about the nation's shortage of software engineers, and told Obama that he was "headed for a one-term presidency". Jobs proposed that any foreign student who got an engineering degree at a US university should automatically be offered a green card. After the meeting, Jobs commented, "The president is very smart, but he kept explaining to us reasons why things can't get done . . . . It infuriates me".
</p>


    </div>
    </div>

    </div>
  )
}